### ISSUE TITLE
Something broken with zlib vs. libzlib files (or run-export)

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/zlib-feedstock#65] opened 2022-08-15 16:58 UTC
Currently the output `libzlib` [contains](https://github.com/regro/libcfgraph/blob/master/artifacts/libzlib/conda-forge/linux-64/libzlib-1.2.12-h166bdaf_2.json#L212-L215) (e.g. on linux):
```
 "files": [
  "lib/libz.so.1",
  "lib/libz.so.1.2.12"
 ],
```
whereas `zlib` [contains](https://github.com/regro/libcfgraph/blob/master/artifacts/zlib/conda-forge/linux-64/zlib-1.2.12-h166bdaf_2.json#L212-L218):
```
 "files": [
  "include/zconf.h",
  "include/zlib.h",
  "lib/libz.a",
  "lib/libz.so",
  "lib/pkgconfig/zlib.pc"
 ],
```

On top of that, `zlib` only run-exports a dependence on `libzlib` (and not `zlib`), so stuff like `libz.so` (and the package config) will not be found, leading i.a. (AFAICT) to stuff [like](https://github.com/conda-forge/googleapis-cpp-feedstock/pull/35):
```
CMake Error at /home/conda/feedstock_root/build_artifacts/googleapis-cpp_1660576007096/[...]/lib/cmake/grpc/gRPCTargets.cmake:77 (set_target_properties):
  The link interface of target "gRPC::grpc" contains:

    ZLIB::ZLIB

  but the target was not found.
```
despite the respective package run-depending on libzlib (based on having zlib as a host-dep for grpc-cpp).

### As far as I can tell, we need to either:
* run-export zlib (instead of libzlib) from zlib output
* make zlib a thin wrapper around zlib, so that the contained files are identical

PTAL @conda-forge/zlib
CC @hmaarrfk (since you added https://github.com/conda-forge/grpc-cpp-feedstock/pull/197)

**Comment by isuruf** [comment] 2022-08-15 17:04
If you want `libz.so`, i.e. you want to link to the shared library, then you need to add `zlib` to `host` which will then give you `libz.so.1` at runtime. This is intentional.

**Comment by h-vetinari** [comment] 2022-08-15 17:16
OK, fine if file separation is intentional as-is. But why shouldn't zlib run-export zlib? Removing the run-dep `zlib` from `grpc-cpp` broke downstream builds, and quite clearly, @hmaarrfk assumed that things would keep working with just the run-export from the zlib host-dep.

So how should this be fixed (here or in grpc-cpp), in your opinion?

**Comment by hmaarrfk** [comment] 2022-08-15 17:52
"Broke downstream builds" is a little harsh. Those builds were missing a dependency in the first place. 

From the CMake files:
```
CMake Error at /home/conda/feedstock_root/build_artifacts/googleapis-cpp_1660576007096/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/cmake/grpc/gRPCTargets.cmake:77 (set_target_properties):
  The link interface of target "gRPC::grpc" contains:

    ZLIB::ZLIB
```

If your cmake file requires the zlib compilation headers, it should depend on the `zlib` package, as before.

In the package that "broke", I'm not particularly sure how zlib is being used since conda can't detect its usage in the final output. You can ask upstream to remove the dependency if you want too.

Unless something broke for a downstream user, I'm not so inclined to change anything here.

**Comment by hmaarrfk** [comment] 2022-08-15 17:52
There is, unfortunately some churn in managing dependencies, but it seems that you were transitively depending on the zlib interface, and that you should, instead be explicitely depending on it.

**Comment by hmaarrfk** [comment] 2022-08-15 17:56
> But why shouldn't zlib run-export zlib

This is somewhat unfortunate in the way that conda-forge was built up. There isn't a strict naming convention for packages that are libraries, and utility functions.

**Comment by hmaarrfk** [comment] 2022-08-15 18:09
I'm going to close this since after adding the dependency, the builds in question passed.

The transitive dependency should not have been relied in the first place. I don't think there is an issue with old builds given that `libzlib` will be installed for them too.

**Comment by h-vetinari** [comment] 2022-08-15 18:11
> This is somewhat unfortunate in the way that conda-forge was built up.

I was thinking about this as well. this feedstock also doesn't match the most common lib-scheme we have so far (libxyz contains the so+headers). I think we can document these things and evolve there over time. Things are not set in stone (and we can take as much time as we want to converge to a better place).

> "Broke downstream builds" is a little harsh. Those builds were missing a dependency in the first place.

It wasn't my intention to be harsh, sorry if it came across like that. From how I read the cmake logs, it's breakage in the sense that grpc cannot survive a cmake configure step anymore, since the zlib that grpc needs isn't there anymore. It seems like the wrong approach to add zlib to the downstream packages...?

**Comment by hmaarrfk** [comment] 2022-08-15 18:16
Hmm, ok I get it, yeah, it is strange to me that grpc requires zlib explicitely. This is indeed unfortunate. Maybe we should fix the problem in grpc. It shouldn't require the zlib build files to be installed.

**Comment by hmaarrfk** [comment] 2022-08-15 18:21
Hmm yeah... it seems that:

https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/cmake/zlib.cmake#L55

```
  if(TARGET ZLIB::ZLIB)
    set(_gRPC_ZLIB_LIBRARIES ZLIB::ZLIB)
```

should definitely be declared as private. Many people forget to add that qualifier in cmake. 

Maybe we can try a small patch:

```patch
-     set(_gRPC_ZLIB_LIBRARIES ZLIB::ZLIB)
+     set(_gRPC_ZLIB_LIBRARIES PRIVATE ZLIB::ZLIB)
```

https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents

**Comment by hmaarrfk** [comment] 2022-08-15 18:22
FYI, eventually that variable gets passed to: https://github.com/grpc/grpc/blob/3ec0e29bcf48e5774a1b124f0edf581b7ca40055/templates/CMakeLists.txt.template

**Comment by hmaarrfk** [comment] 2022-08-15 18:23
```
diff --git a/cmake/zlib.cmake b/cmake/zlib.cmake
index 9d658921d3..0e9ecb695c 100644
--- a/cmake/zlib.cmake
+++ b/cmake/zlib.cmake
@@ -52,9 +52,9 @@ elseif(gRPC_ZLIB_PROVIDER STREQUAL "package")
   find_package(ZLIB REQUIRED)

   if(TARGET ZLIB::ZLIB)
-    set(_gRPC_ZLIB_LIBRARIES ZLIB::ZLIB)
+    set(_gRPC_ZLIB_LIBRARIES PRIVATE ZLIB::ZLIB)
   else()
-    set(_gRPC_ZLIB_LIBRARIES ${ZLIB_LIBRARIES})
+    set(_gRPC_ZLIB_LIBRARIES PRIVATE ${ZLIB_LIBRARIES})
   endif()
   set(_gRPC_ZLIB_INCLUDE_DIR ${ZLIB_INCLUDE_DIRS})
   set(_gRPC_FIND_ZLIB "if(NOT ZLIB_FOUND)\n  find_package(ZLIB)\nendif()")
```

**Comment by h-vetinari** [comment] 2022-08-15 18:26
Ok, that makes a lot of sense. I think such a patch would be a good idea for all extant grpc builds (where the run-dep was removed), at least 1.46-1.48

**Comment by hmaarrfk** [comment] 2022-08-15 18:31
I generally think that this kind of patch is upstreamable, but.... my experience is that google doesn't care about non "monorepo" builds and that they typically don't like to deal with this kind of churn.

Sorry for the bug in the GPRC feedstock.

**Comment by h-vetinari** [comment] 2022-08-15 18:36
> I generally think that this kind of patch is upstreamable, but...

Worth a try? I've also had good experiences with contributing to Google projects recently, but it's very project-dependent...

> Sorry for the bug in the GPRC feedstock.

No worries at all, thanks for the analysis & the fix!

**Comment by sr99622** [comment] 2022-08-20 19:54
quoting isuru - 
If you want libz.so, i.e. you want to link to the shared library, then you need to add zlib to host which will then give you libz.so.1 at runtime. This is intentional.

Yes this fix does work, but the problem comes as a surprise, especially if you are doing a conda-build with a lot of moving parts.  Keeping the libz.so file intact as it was previously seems like a pretty small price to pay against the benefit of eliminating it, of which I'm not sure that there is much.  Most lower level libraries do include the .so as a symbolic link, so it seems like removing it for libz goes against convention, which is confusing.

I think my basic message would be that a lot of libraries have dependency on libz and most conda build scenarios would assume that it will be installed as a dependency which would include libz.so.  I have to believe that there are many more potential build failures that will occur as time goes on and projects are updated.

Thank you so much for reading, your attention is appreciated.

**Comment by hmaarrfk** [comment] 2022-08-20 21:01
Fundamentally, if your library depends on libz.so and you don't explicitely depend on it, when a new version comes out, it will not be rebuilt by the migrator. You may get serious ABI breakage that will hurt your end users.

The issue is masked in this particular case because libz is somewhat stable, but it is still not a good way to about things as the ecosystem grows.

The challenge with grpc is that they generate their cmake files, and thus, we need to learn how to patch their generator, and not just their cmake files.

**Comment by sr99622** [comment] 2022-08-21 14:24
For background reference, my issue is not with grpc, but with a project that has a dependency on SDL_ttf, which in turn has dependency on freetype, png and zlib.  The meta.yaml does not explicitly define these secondary dependencies, as SDL_ttf will install them, and my application does not use the secondary libraries directly, it only calls SDL_ttf.  The cmake find_package command is used to find the libraries for linking.

My use case involves a pybind11 application that uses conda build to install dependency libraries.  A working conda build that I have used before started failing.  The removal of the zlib shared library caused two problems from my perspective:

1.) The conda build will fail, which brought me to this thread.

2.) Building the application locally using python setup.py install will also fail.

The first issue can be fixed by adding zlib to the host section of meta.yaml, and the second by adding zlib to the run section . 
 These are obviously not major problems, but they are difficult to trouble shoot because of the complexity of the build process and the unexpected occurrence of the failure.  I would posit further that zlib is breaking convention by not including the shared library as most other packages I can think of do include the file.  That's not to say that one way is right or wrong, but it creates confusion in an already complex situation.

Please forgive me asking, but I am not sure what is meant by "rebuilt by the migrator".

I hope I am bringing useful information to the discussion, your feedback is greatly appeciated.

**Comment by hmaarrfk** [comment] 2022-08-21 15:04
> A working conda build that I have used before started failing. 

I know this can be frustrating. If your project is open source, it really helps troubleshooting if you can just link us to a log. Again, without specifics, I would bet that you are missing an explict dependency on a the development files for `zlib`.

> The removal of the zlib shared library

We didn't remove the shared library, we only removed files that are required for others to `link` to `zlib`. All files required to USE the `zlib` shared libraries you have linked to previously.

> The first issue can be fixed by [...]

Unfortunately, I don't want to get into discussing hypothetical situation without looking at specific build files or code. If you can provide a minimum reproducing example, I am happy to discuss how to help you move forward.

Without looking at any specific reproducing example, I would add `zlib` as a dependency in the `host` section (and maybe even in the `run` section) to your `meta.yaml`. This is what we did with grpc.

>  but I am not sure what is meant by "rebuilt by the migrator".

One of the technologies that ensures that conda-forge packages are compatible is that packages declare what future versions they are compatible with. (A tricky propositon but lets go with that for now). When a new incompatible version is detected, the "migrator" will rebuild all packages that explicitely depend on this package.

> I hope I am bringing useful information to the discussion, your feedback is greatly appeciated.

You are. One thing that would be better is to link to an actual issue log. In general, piggy packing on other issues is hard because while the symptoms are the "same", their causes are often not. We've worked with h-ventinari to get to the bottom of his issue (he linked to an explicit log) so I am tempted to close this. This would allow you to open a new issue, with the explicit information we would require to help you resolve it.

**Comment by sr99622** [comment] 2022-08-21 16:00
Understood, and point taken regarding piggy backing on other issues.  I have been able to resolve my issues based on the information in this thread, thank you so much for your help.

**Comment by hmaarrfk** [comment] 2022-08-21 16:36
glad you got up and running again.

**Closed as completed by hmaarrfk** 2022-08-21 16:36 UTC
